#162948911 Enable Social login via Google, Facebook and Twitter
andela/ah-alpha pull request #18
Opened 2019-01-24 08:22 UTC by Deekerubo

**What does this PR do?**
This PR enables social Login using Facebook, Twitter and Google accounts. 

**Description of Task to be completed?**
A user cannot Login with a pre-existing social media account. This PR can:
-Test Facebook authentication
-Test Twitter authentication
-Test Google authentication
Users can be able to get their personal information from these social sites. The information enables a user to be authenticated to other social sites and navigate it.

**How should this be manually tested?**
Clone this [repository](https://github.com/andela/ah-alpha.git) then navigate to `ft-social-auth-162948911`
Set the environment, update the requirements.txt file and configure the database.
Get token from:
[Facebook Developer](https://developers.facebook.com/apps)
[Twitter Developer](https://developer.twitter.com/en/apps)
[Google Developer](https://developers.google.com/oauthplayground)

In Your Postman pass the provider and access_token under this url `http://127.0.0.1:8000/api/v1/social_auth/`
Get the access_token from:
[Google Developer](https://developers.google.com/oauthplayground)
```
{
	"provider": "google-oauth2",
     "access_token": ""
}
```
[Facebook Developer](https://developers.facebook.com/apps)
```
{
	"provider": "facebook",
     "access_token": ""
}
```
[Twitter Developer](https://developer.twitter.com/en/apps)
```
{
	"provider": "twitter",
     "access_token": ""
}
```
The output should be a dictionary returning the name, email and access_token from the provider as below;
```
{
    "user": {
        "email": "alphaandela@gmail.com",
        "username": "alphaandela",
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6bnVsbCwiaWF0IjoxNTQ4MzI3MzA1fQ.zEsh9MvDM5uFzjQoklOu-SIGaA6vODN7k36n1Bz6RdY"
    
}
```

**What are the relevant pivotal tracker stories?**
[#162948911](https://www.pivotaltracker.com/story/show/162948911)

2019-01-24 22:17 UTC, danuluma commented
Please fix the merge conflicts

2019-01-24 22:18 UTC, danuluma approved these changes

2019-01-28 08:23 UTC, boltonotieno requested changes
You have too many blank lines at the end of the test file. Kindly remove them

2019-01-28 08:23 UTC, boltonotieno commented on authors/apps/authentication/backends.py
> +SECRET_KEY = settings.SECRET_KEY
There are two secret keys with the same value. You can use one

2019-01-28 08:23 UTC, boltonotieno commented on authors/apps/authentication/tests/test_social_auth.py
> +# from rest_framework import status
Remove the commented line 6

2019-01-28 08:41 UTC, Deekerubo commented on authors/apps/authentication/backends.py
> +SECRET_KEY = settings.SECRET_KEY
Thank you. Done!

2019-01-28 19:05 UTC, boltonotieno approved these changes

2019-01-28 19:14 UTC, merged