#162948895 Test Driven Development
andela/ah-alpha pull request #9
Opened 2019-01-14 11:10 UTC by tesh254

#### What does this PR do?

This pr contains  a couple of tests, it approaches the TDD way

#### Description of the task to be accomplished?

* Create a couple of test for authentication

#### How can this be manually tested?

* Clone this repo
* CD into the project directory
* Install dependencies `pip install -r requirements.txt`
* Run this command to run tests `python3 manage.py runserver`

#### Background context?

* Use Python3 version `3.7 or above 3.x`
* Use Django version `2.x`

#### Related Pivotal Tracker stories?

* [#162948895](https://www.pivotaltracker.com/story/show/162948895)

2019-01-14 11:29 UTC, jamesbeamie approved these changes

2019-01-14 11:36 UTC, Ruiru11 approved these changes

2019-01-14 11:51 UTC, danuluma approved these changes

2019-01-15 09:42 UTC, BoltC0rt3z commented
The command for running tests is not correct. It should be `python3 manage.py tests

2019-01-15 09:48 UTC, tesh254 commented
Fixed

2019-01-16 06:25 UTC, frankip requested changes

2019-01-16 06:25 UTC, frankip commented on authors/apps/authentication/tests/test_registration.py
> +        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
@tesh254 you need to also assert for the status messages

2019-01-16 07:52 UTC, frankip approved these changes

2019-01-16 07:53 UTC, frankip approved these changes
LGTM

2019-01-16 07:53 UTC, merged